/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'baseAmount' : IDL.Nat,
});
export const Quest = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'date' : IDL.Text,
  'completed' : IDL.Bool,
});
export const Profile = IDL.Record({
  'xp' : IDL.Nat,
  'weight' : IDL.Nat,
  'streak' : IDL.Nat,
  'quest' : IDL.Opt(Quest),
  'level' : IDL.Nat,
  'lastQuestDate' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'completeTask' : IDL.Func([IDL.Text], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAllProfilesByLevel' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getQuest' : IDL.Func([], [Quest], []),
  'initializeProfile' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'baseAmount' : IDL.Nat,
  });
  const Quest = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'date' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const Profile = IDL.Record({
    'xp' : IDL.Nat,
    'weight' : IDL.Nat,
    'streak' : IDL.Nat,
    'quest' : IDL.Opt(Quest),
    'level' : IDL.Nat,
    'lastQuestDate' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'completeTask' : IDL.Func([IDL.Text], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAllProfilesByLevel' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getQuest' : IDL.Func([], [Quest], []),
    'initializeProfile' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };